class LessonModel {
  final String id;
  final String title;
  final String description;
  final String whatToLookFor;
  final String actionableAdvice;

  const LessonModel({
    required this.id,
    required this.title,
    required this.description,
    required this.whatToLookFor,
    required this.actionableAdvice,
  });

  // This maps the backend check 'name' to the specific lesson content
  static const Map<String, LessonModel> catalogue = {
    'authority_spoofing': LessonModel(
      id: 'authority_spoofing',
      title: 'Domain Masking (@)',
      description: 'Attackers use the "@" symbol to hide the real destination of a link.',
      whatToLookFor: 'Look closely at the URL. Everything before the "@" is ignored by the browser.',
      actionableAdvice: 'Never trust a link that contains an "@" symbol in the middle of the domain.',
    ),
    'punycode': LessonModel(
      id: 'punycode',
      title: 'Homograph Attack',
      description: 'Attackers use characters from other languages (like Cyrillic) that look identical to English letters.',
      whatToLookFor: 'Look for "xn--" at the start of the domain, or characters that look slightly strange.',
      actionableAdvice: 'Type critical URLs (like your bank) manually instead of clicking links.',
    ),
    'ip_literal': LessonModel(
      id: 'ip_literal',
      title: 'Hidden Behind Numbers',
      description: 'Instead of a registered name (like google.com), the link uses a raw IP address.',
      whatToLookFor: 'A URL that starts with numbers and dots (e.g., http://192.168.1.1).',
      actionableAdvice: 'Legitimate companies rarely use raw IPs for consumer links. Do not proceed.',
    ),
    'nested_short': LessonModel(
      id: 'nested_short',
      title: 'Nested Shorteners',
      description: 'The attacker is hiding the final destination by putting a shortened link inside another shortened link.',
      whatToLookFor: 'If a bit.ly link redirects to a tinyurl.com link, it is highly suspicious.',
      actionableAdvice: 'Use link expander tools or our scanner to see the final destination before logging in.',
    ),
    'dga_entropy': LessonModel(
      id: 'dga_entropy',
      title: 'Machine-Generated URL',
      description: 'The domain name consists of random characters generated by malware.',
      whatToLookFor: 'Look for domains that look like gibberish (e.g., "xytqbz129.com").',
      actionableAdvice: 'If you cannot pronounce it and it looks like a password, it is likely malicious.',
    ),
    'generic': LessonModel(
      id: 'generic',
      title: 'Suspicious Activity Detected',
      description: 'This QR code triggered our heuristic security filters.',
      whatToLookFor: 'Look for poor grammar, urgent requests, and requests for sensitive info.',
      actionableAdvice: 'When in doubt, contact the sender through a verified, separate channel.',
    ),
  };
}
